---
title: "OneK1K-TWAS"
author: "Fei Qin"
date: "2025-03-18"
output: pdf_document
---

```{r, message=FALSE, warning = FALSE}
setwd(paste0("C:\\Users\\qinf2\\OneDrive - National Institutes of Health\\Kai Yu\\eQTL\\Manuscript\\Submission\\Package\\OneK1K-TWAS-main\\OneK1K-TWAS-main\\data"))
library(data.table)

############################ Fiting hom and het components for each cell type #############################
###########################################################################################################
###########################################################################################################

genename <- "ENSG00000000457"
X1 <- paste0("Exp/", genename, "/snpexp")
Y1 <- paste0("Exp/", genename, "/y/")
cov1 <- "Cov/"
Out1 <- "results/"
SNP1 <- paste0("Exp/", genename, "/snppos.txt")
Pre1 <- genename

library(scTWAS)
hom_het_model(X_file=X1,  # Genotype matrix, individuals are row names, no column names. Check examples data for more details.
              Y_file_dir=Y1, # Direction containing only the expression files, individuals are row names, no column names. Check examples data for more details.
              cov_file_dir=cov1, # Cov file direction, should share the same prefix as the expression files Check examples data for more details.
              out_dir=Out1,  # output CV predictors and other coefficients.
              snps=SNP1,  # A tab-delimited txt file containing snp information. Six columns.
              gene_name=Pre1) # Add this prefix to all the saved results files  
```


```{r, message=FALSE, warning = FALSE}
################################### Second step ######################################
######  Fitting models using hom and het components generated in the first step ######
######################################################################################
Model_fit(Gname=genename)

  
######################################################################################
###### Combing coefficients from above two steps and prepare for weights file   ######
######################################################################################    
Weights_pre(G_name=genename, in_dir="results/")


######################################################################################
############# Generating weights files required for FUSION TWAS ######################
######################################################################################   
Weights_gen(G_name=genename, in_dir="results/", out_dir="weights/")
```